version: '3'
services:
  # rust-app:
  #   build:
  #     context: .  # Use the current directory as the build context
  #     dockerfile: ./back/Dockerfile  # Name of your Dockerfile for the Rust app
  #   ports:
  #     - "8080:8080"  # Map port 8080 to the host
  #   depends_on:
  #     - postgres-db  # Ensure the PostgreSQL service is ready before starting the Rust app

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: empty
      POSTGRES_DB: muzz_db
    ports:
      - "5432:5432"  # Map port 5432 to the host
